version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_PASSWORD=max123456
    networks:
      - app_network
  app:
    image: iotg23/tg-backend
    pull_policy: if_not_present
    depends_on:
      - db
    ports:
      - "5050:80"
    environment:
      - JWT__Issuer=value
      - JWT__Audience=value
      - JWT__Key=valuevaluevalue123valuevalue123456789
      - ASPNETCORE_ENVIRONMENT=Development
      - TFA__Key=secretkey
      - TFA__Issuer=tg-backend
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
    
